// auth

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const USER_LOADED = 'USER_LOADED';
const AUTH_ERROR = 'AUTH_ERROR';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGOUT = 'LOGOUT';
const CLEAR_ERRORS = 'CLEAR_ERRORS';

// bullets

const SET_BULLET_LOADING = 'SET_BULLET_LOADING';
const GET_BULLETS = 'GET_BULLETS';
const ADD_BULLET = 'ADD_BULLET';
const DELETE_BULLET = 'DELETE_BULLET';
const SET_CURRENT = 'SET_CURRENT';
const SET_UPDATE = 'SET_UPDATE';
const CLEAR_CURRENT = 'CLEAR_CURRENT';
const UPDATE_BULLET = 'UPDATE_BULLET';
const BULLETS_ERROR = 'BULLETS_ERROR';

module.exports = {
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  USER_LOADED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT,
  CLEAR_ERRORS,
  SET_BULLET_LOADING,
  GET_BULLETS,
  ADD_BULLET,
  UPDATE_BULLET,
  DELETE_BULLET,
  SET_CURRENT,
  CLEAR_CURRENT,
  BULLETS_ERROR,
  SET_UPDATE
}
